import Head from 'next/head'
import { AppShell, createStyles, Flex, Footer, Header, Text } from '@mantine/core'

const useStyles = createStyles((theme) => ({
  container: {
    height: 45,
    display: "flex",
    maxWidth: "768px",
    boxSizing: 'border-box',
    marginLeft: 'auto',
    marginRight: 'auto',
    flexDirection: 'column',
  },
  test: {
    background: '#0d1117',
    height: '100vh%'

  }
}));

export default function Home() {
  const { classes } = useStyles();
  return (
    <div className={classes.test}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="md" className={classes.container}
        header={<Header height={45} className={classes.container} p="xs">{/* Header content */}</Header>}
        footer={<Footer height={45} className={classes.container} >{
          <Flex h={45} align="center">
            <Text size='xs' px='sm'>Copyright © 2021-2023 Puntogris </Text>
          </Flex>
        }</Footer>}
        styles={(theme) => ({
          main: { backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0] },
        })}
      >
        {
      

        }
      </AppShell>
    </div>
  )
}
