import Head from 'next/head'
import { AppShell, createStyles, Flex, Footer, Group, Header, Text } from '@mantine/core'
import Link from 'next/link';

const useStyles = createStyles((theme) => ({
  container: {
    display: "flex",
    maxWidth: "768px",
    boxSizing: 'border-box',
    marginLeft: 'auto',
    marginRight: 'auto',
    flexDirection: 'column'
  },
  test: {
    background: '#0d1117',
    height: '100vh%'

  },
  link: {
    textDecoration: 'none',
    color: theme.colors.dark[0],
    fontSize: theme.fontSizes.sm,
    fontWeight: 'bold',
    '&:hover': {
      color: theme.colors.dark[2],
    },
  },
}));

export default function Home() {
  const { classes } = useStyles();
  return (
    <div className={classes.test}>
      <Head>
        <title>Puntogris</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="md" className={classes.container}
        header={
          <Header height={55} className={classes.container} py="xs">{

            <Group h={55}>
              <Link key={""} href={""} className={classes.link}>
                Home
              </Link>
              <Link key={""} href={""} className={classes.link}>
                Projects
              </Link>

            </Group>

          }</Header>}
        footer={<Footer height={55} className={classes.container} >{
          <Flex h={55} align="center">
            <Text c="dimmed" size='sm' px='sm'>Copyright © 2021-2023 Puntogris </Text>
          </Flex>
        }</Footer>}
        styles={(theme) => ({
          main: { backgroundColor: '#0d1117' },
        })}
      >
        {


        }
      </AppShell>
    </div>
  )
}
